apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: etcd
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~4.7
spec:
  releaseName: etcd3
  targetNamespace: demo
  timeout: 300
  resetValues: true
  forceUpgrade: true
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: etcd
    version: 4.7.5
  values:
    envVarsConfigMap: etcd-env      
  auth.rbac.enabled : true
  auth.rbac.rootPassword: password
