apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: etcd
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~3.1
spec:
  releaseName: etcd3
  targetNamespace: demo
  timeout: 300
  resetValues: true
  forceUpgrade: true
  chart:
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    name: etcd
    version: 0.7.4
  values:
    replicas: 1
    extraEnvs: 
      - ETCD_LOGGER=zap
