---
# This secret should be stored in Git encrypted
# Sealed Secrets example: https://github.com/stefanprodan/gitops-helm#managing-kubernetes-secrets
apiVersion: v1
kind: Secret
metadata:
  name: etcd-auth
  namespace: demo
data:
  etcd-root-password: Rnd3ZzlBdWVKYg==
